### ISSUE TITLE
v3.0.2 fails to resolve "request"

### ISSUE THREAD

**Issue by doolse** [shinnn/load-from-cwd-or-npm#1]
This causes the purescript installer npm package to fail - purescript/npm-installer#12

```js
const loadFromCwdOrNpm = require("load-from-cwd-or-npm");

loadFromCwdOrNpm("request").then(console.log);
```
`[Function: PassThrough]`

**Comment by shinnn** [comment]
Fixed in https://github.com/shinnn/load-from-cwd-or-npm/commit/f5010f2f0a37faf93411f654eed63f3b2807d9b0.

**Comment by shinnn** [comment]
Ah, probably I fixed another bug I found that is unrelated to https://github.com/purescript/npm-installer/issues/12.

Actually the problem described in https://github.com/purescript/npm-installer/issues/12#issue-464853208 still seem to happen.
